/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AmazonOrderScraperApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AutomationHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GoogleGenerativeAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LedgerExportArtifacts": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "LedgerTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PlaidClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PlaidSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VenmoEmailArtifacts": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "VenmoEmailFailures": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "VenmoEmailHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "YnabImportArtifacts": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "YnabImportWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}

import "sst"
export {}