import { mkdtemp, readFile, rm } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import {
    formatApplicationVersionForDisplay,
    isApplicationVersionTimestamp,
} from "@/lib/application-version";

const versionWriterPath = join(
    process.cwd(),
    "scripts/write-application-version.mjs",
);

describe("application version", () => {
    it("recognizes canonical ISO UTC timestamps", () => {
        expect(isApplicationVersionTimestamp("2026-07-18T12:34:56.789Z")).toBe(
            true,
        );
        expect(isApplicationVersionTimestamp("unknown")).toBe(false);
        expect(isApplicationVersionTimestamp("2026-07-18")).toBe(false);
        expect(isApplicationVersionTimestamp(undefined)).toBe(false);
    });

    it("formats the timestamp in the browser local time zone", () => {
        expect(
            formatApplicationVersionForDisplay("2026-07-18T12:34:56.789Z"),
        ).toBe(
            new Intl.DateTimeFormat(undefined, {
                dateStyle: "medium",
                timeStyle: "short",
            }).format(new Date("2026-07-18T12:34:56.789Z")),
        );
    });

    it("writes a generated timestamp module", async () => {
        const directory = await mkdtemp(join(tmpdir(), "budgeted-version-"));
        const outputPath = join(directory, "application-version.generated.ts");
        const timestamp = "2026-07-18T12:34:56.789Z";

        try {
            execFileSync(process.execPath, [
                versionWriterPath,
                "--timestamp",
                timestamp,
                "--output",
                outputPath,
            ]);

            await expect(readFile(outputPath, "utf8")).resolves.toBe(
                [
                    "// Generated by the pre-commit hook. Do not edit manually.",
                    `export const GENERATED_APPLICATION_VERSION = ${JSON.stringify(timestamp)};`,
                    "",
                ].join("\n"),
            );
        } finally {
            await rm(directory, { force: true, recursive: true });
        }
    });
});
